# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steam_hardware.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'steam_hardware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14steam_hardware.proto\x12\x0bsteam.store\"d\n\x17GetHardwareItemsRequest\x12\x13\n\x0bhardware_id\x18\x01 \x01(\r\x12\x34\n\x07options\x18\x02 \x01(\x0b\x32#.steam.store.HardwareRequestOptions\"@\n\x16HardwareRequestOptions\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\"E\n\x18GetHardwareItemsResponse\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.steam.store.CHardwareItem\"N\n\rCHardwareItem\x12=\n\x0fpackage_details\x18\x01 \x01(\x0b\x32$.steam.store.CHardwarePackageDetails\"\x95\x04\n\x17\x43HardwarePackageDetails\x12\x11\n\tpackageid\x18\x01 \x01(\r\x12\x1b\n\x13inventory_available\x18\x03 \x01(\x08\x12\x1b\n\x13high_pending_orders\x18\x04 \x01(\x08\x12*\n\"account_restricted_from_purchasing\x18\x05 \x01(\x08\x12\x1c\n\x14requires_reservation\x18\x06 \x01(\x08\x12$\n\x1crtime_estimated_notification\x18\x07 \x01(\r\x12\x1a\n\x12notification_token\x18\x08 \x01(\t\x12\x19\n\x11reservation_state\x18\t \x01(\x05\x12\x0f\n\x07\x65xpired\x18\n \x01(\x08\x12\x14\n\x0ctime_expires\x18\x0b \x01(\r\x12\x15\n\rtime_reserved\x18\x0c \x01(\r\x12\x1f\n\x17\x61llow_quantity_purchase\x18\r \x01(\x08\x12!\n\x19max_quantity_per_purchase\x18\x0e \x01(\x05\x12!\n\x19\x61llow_purchase_in_country\x18\x0f \x01(\x08\x12\x30\n(estimated_delivery_soonest_business_days\x18\x11 \x01(\r\x12/\n\'estimated_delivery_latest_business_days\x18\x12 \x01(\r\"/\n\x11HardwareConstants\x12\x1a\n\x10STEAM_CONTROLLER\x18\x86\xf4T \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steam_hardware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHARDWAREITEMSREQUEST']._serialized_start=37
  _globals['_GETHARDWAREITEMSREQUEST']._serialized_end=137
  _globals['_HARDWAREREQUESTOPTIONS']._serialized_start=139
  _globals['_HARDWAREREQUESTOPTIONS']._serialized_end=203
  _globals['_GETHARDWAREITEMSRESPONSE']._serialized_start=205
  _globals['_GETHARDWAREITEMSRESPONSE']._serialized_end=274
  _globals['_CHARDWAREITEM']._serialized_start=276
  _globals['_CHARDWAREITEM']._serialized_end=354
  _globals['_CHARDWAREPACKAGEDETAILS']._serialized_start=357
  _globals['_CHARDWAREPACKAGEDETAILS']._serialized_end=890
  _globals['_HARDWARECONSTANTS']._serialized_start=892
  _globals['_HARDWARECONSTANTS']._serialized_end=939
# @@protoc_insertion_point(module_scope)
